### ISSUE TITLE
List of software and containers

### ISSUE THREAD

**Issue by ypriverol** [BioDocker/specifications#1]
Software's to be installed and deployed:
- [ ]  TTP (Including the web).
- [ ]  SpectraST alone.
- [ ]  R Container 
     - [ ]  Biocoductor (https://github.com/Bioconductor/bioc_docker)
     - [ ]  aLFQ (http://www.ncbi.nlm.nih.gov/pubmed/24753486)
     - [ ]  customProDB (http://www.bioconductor.org/packages/release/bioc/html/customProDB.html)
     - [ ]  Msbase (http://www.bioconductor.org/packages/release/bioc/html/MSnbase.html)
- [ ] SearchGUI
- [x] DeNovoSearchGUI 
- [ ] PeptideShacker
- [x] OpenMS
- [ ] De novo tools:
    - [x] PepNovo+  
- [ ] DIA-Umpire
- [ ] Fido

**Comment by bgruening** [comment]
SearchGUI and PeptideShacker as commandline tools?
Also have a look at:
* https://github.com/galaxyproject/docker-build/tree/master/tpp
* https://github.com/galaxyproteomics/tools-galaxyp/tree/master/packages

**Comment by Leprevost** [comment]
@bgruening yes, they also work with a CLI, at first I thought about setting the GUI, but I'm not sure if we set a different container for the CLI.

**Comment by ypriverol** [comment]
Close moved to https://github.com/BioDocker/specifications/issues/1
