### ISSUE TITLE
Domain Configuration

### ISSUE THREAD

**Issue by Leprevost** [BioDocker/specifications#10]
@ypriverol I have an active Mailgun account, since you have the domains now, I can set an e-mail with the `@biodocker` extension. I can route the incoming e-mail to both of us and at the same time, or create individual e-mails.

**Comment by ypriverol** [comment]
@Leprevost I create already a gmail account that we can use biodockers@gmail.com, if you are agree we can use it in every place.. in the future we can use our domain.

**Comment by Leprevost** [comment]
sure, im ok with that

**Comment by ypriverol** [comment]
We can keep the gmail domain for now.
