### ISSUE TITLE
A common container for all the containers

### ISSUE THREAD

**Issue by ypriverol** [BioDocker/specifications#4]
@hroest @BioDocker/contributors @Leprevost One of the contributors sent me an email, I attached:

Some docker containers 
   - pyProphet, see here https://github.com/hroest/docker_files -- the
     pyprophet algorithm is a redevelopment of mProphet, our original
     algorithm for scoring targeted proteomics data. 
     It would be nice to have some standardized "boilerplate docker code" around for this
     project which would make the interaction with the docker containers in
     the library somewhat standardized. 
     In terms of standardization I think it would be really helpful and it would be
     much appreciated if there were some sort of "how-to" with a few things that the docker containers    
     should provide -- or maybe a template docker file with a section **"ENTER YOUR CODE HERE"** 
     which would make it easier for people to migrate their projects to docker. 

     I have seen https://github.com/BioDocker/OpenMS/blob/master/1.11.1-3/Dockerfile which seems to 
     contain some of that -- maybe you could add a "template.docker" file to 
      https://github.com/BioDocker/specifications
@Leprevost It would be good to discuss this ideas.

**Comment by ypriverol** [comment]
@ppedrioli mention:
    "security implications of running docker and how they will impact the success of BioDocker. For 
    instance, some IT groups doesn't currently allow docker to run on our HPCs."

**Comment by ypriverol** [comment]
what about this: 
   - [ ] Create a common "default" container for all the docker containers as @hroest mention and 
         try to setup and control in this docker container all the security issues and include this in the 
         specification. All containers will be deploy using this original container or docker image. This 
         original container will futfil most of the specifications from other initatives such as opencontainers    
          (https://github.com/opencontainers)

What is the best option to provide a way of automatic deployment for some applications, can we do something simple in this direction @Leprevost.. something like deploy here your .gz file. ?

**Comment by Leprevost** [comment]
Hey @hroest @BioDocker/contributors

I`m planning to create a template Dockerfile for everyone to use and also a simple guide on how to organize the directories and files in order to containerize something. I will let you know about this.

**Comment by ypriverol** [comment]
@Leprevost Can we make this information part of the specifications, the way of organising the information (the folders, variables, etc) part of the specifications, can we make this as close as possible to other initiatives such as opencontainers.

**Comment by Leprevost** [comment]
@ppedrioli @ypriverol 

Running Docker on some environments still brings some issues to the sysadmins, there are a few things that must be addressed. Previous versions of Docker found on legacy systems or OS dedicated to stability, like CentOS, they need you to be root to execute the daemon. The last version of Docker added the option to create a separate user group in your system with the necessary permissions to run the daemon. It is also important to remember that this is a very new technology and people are still getting used to. With more usage and acceptance this issues will change. Docker now runs on major cloud systems like dotCloud, Openshift, Amazon and Google, so I think this will be resolved in a near future.

**Comment by Leprevost** [comment]
@ypriverol we can work to make this as more compatible as possible to the general guidelines for containers, but I don't think we need to care that much with the open container initiative. I think what they are trying to do is to set the standards for new container-driven technologies. There are new companies and Docker-like systems appearing now. By sticking to Docker general guidelines I think we are OK. The whole concept and even the mechanics behind the source-code that are designated by the open containers initiative came from Docker, they donated their specifications to the movement.

**Comment by ypriverol** [comment]
@Leprevost Ok, then we can close this issue when you release the first docker template.. and then we can deploy all the applications.

**Comment by Leprevost** [comment]
Dear all @BioDocker/contributors 

The wiki now contains a general guideline on how the tempalte should be formatted;

https://github.com/BioDocker/specifications/wiki/Dockerfile-template

Please fell free to make adjustments, comments, suggestions and critics about this. This should be a community-driven designed guideline, so all opinions are welcome.
